filepaths:
  final_optimal_prompts_file: "output/deepseek-coder/optimal_prompts.txt"
  development_set_file: "data/temp_developmentSet.txt"
  reproductive_group_file: "output/deepseek-coder/reproductive_groups.txt"
  G_t_for_iteration_prev_t_file: "output/deepseek-coder/G_t_for_iteration_0.txt" # change per iteration
  G_t_for_iteration_t_file: "output/deepseek-coder/G_t_for_iteration_1.txt" # change per iteration
  prompts_with_scores_file: "output/deepseek-coder/gen_prompts_with_scores.txt"
  gen_code_output_dir: "output/gemini/code/gps-1/evaluation"
  bandit_output_dir: "output/gemini/bandit/gps-1/evaluation"
  test_set_file: "data/testSet.txt"
  test_output_file: "output/deepseek-coder/test_output.txt"
  test_prompts_file: "output/gemini/optimal_prompts.txt"
  evaluation_results_file: "output/gemini/optimal_prompt_evaluation.txt"
  temp_output_dir: "output/deep-seek"

GPS_parameters:
  iterations: 6 # change per iteration
  K: 4
  t: 0 # change per iteration
