filepaths:
  final_optimal_prompts_file: "output/deepseek-coder/optimal_prompts.txt"
  development_set_file: "data/temp_developmentSet.txt"
  reproductive_group_file: "output/deepseek-coder/generated-prompts-1.txt"
  prompts_with_scores_file: "output/deepseek-coder/gen_prompts_with_scores-1-test.txt"
  gen_code_output_dir: "output/deepseek-coder/code/gps-1/training"
  bandit_output_dir: "output/deepseek-coder/bandit/gps-1/training"
  test_set_file: "data/testSet.txt"
  test_output_file: "output/deepseek-coder/test_output.txt"
  test_prompts_file: "data/optimal_prompts.txt"
  evaluation_results_file: "output/optimal_prompt_evaluation.txt"
  temp_output_dir: "output/deep-seek"

GPS_parameters:
  iterations: 1
  K: 4
